meta:
  version: 3
  flow: Classic
  substituting_steps:
    +Magic.DRC: KLayout.Antenna
    +Checker.MagicDRC: Checker.KLayoutAntenna

DESIGN_NAME: combined
VERILOG_FILES: ["dir::src/combined.v", "dir::src/hellorld.v", "dir::src/diceroll.v", "dir::src/nano.v", "dir::src/mc.v", "dir::src/blinker.v", "dir::src/secret_message.v", "dir::src/message.v"]
CLOCK_PERIOD: 50
DIE_AREA: [0, 0, 700, 700]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: AREA 1
ERROR_ON_KLAYOUT_DRC: true
DESIGN_REPAIR_TIE_FANOUT: true
DIODE_ON_PORTS: both
OUTPUT_CAP_LOAD: 180
RUN_CTS: true
DRT_ANTENNA_REPAIR_ITERS: 5
MAX_FANOUT_CONSTRAINT: 6
GRT_ALLOW_CONGESTION: true
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
GRT_ANTENNA_MARGIN: 20
DRT_ANTENNA_MARGIN: 20
IO_PIN_H_LAYER: Metal4
IO_PIN_V_LAYER: Metal3

KLAYOUT_DRC_THREADS: 1
KLAYOUT_DRC_OPTIONS:
  workers: max
  decks: "all,-antenna,-density"

KLAYOUT_ANTENNA_OPTIONS:
  workers: max
  decks: "antenna"

STD_CELL_LIBRARY: "gf180mcu_as_sc_mcu7t3v3"

KLAYOUT_RENDER_RESOLUTION: 8192
KLAYOUT_RENDER_OVERSAMPLING: 3
KLAYOUT_PROPERTIES: dir::../../librelane/gf180mcu_render.lyp
