PWD=$(shell pwd)
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PDK_ROOT ?= $(PWD)/../../gf180mcu
WAVES = 1

COMPILE_ARGS += -DSIM -DPAD_gf180mcu_ocd_io
VERILOG_SOURCES += $(PWD)/tb.v
VERILOG_SOURCES += $(PDK_ROOT)/gf180mcuD/libs.ref/gf180mcu_as_sc_mcu7t3v3/verilog/gf180mcu_as_sc_mcu7t3v3.v
VERILOG_SOURCES += $(PDK_ROOT)/gf180mcuD/libs.ref/gf180mcu_ocd_io/verilog/gf180mcu_ocd_io.v
VERILOG_SOURCES += $(PWD)/../../ip/gf180mcu_ws_ip__qrcode_id/vh/gf180mcu_ws_ip__qrcode_id.v
VERILOG_SOURCES += $(PWD)/../../ip/gf180mcu_ws_ip__project_id/vh/gf180mcu_ws_ip__project_id.v
VERILOG_SOURCES += $(PWD)/../../ip/gf180mcu_ws_ip__shuttle_id/vh/gf180mcu_ws_ip__shuttle_id.v
VERILOG_SOURCES += $(PWD)/../../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
VERILOG_SOURCES += $(PWD)/../../ip/gf180mcu_ws_ip__marker/vh/gf180mcu_ws_ip__marker.v

COMPILE_ARGS += -DUSE_POWER_PINS

ifneq ($(GL),yes)
VERILOG_SOURCES += $(PWD)/../includes.rtl.v
else
COMPILE_ARGS += -DGL_TEST
COMPILE_ARGS += -DFUNCTIONAL
VERILOG_SOURCES += $(PWD)/../includes.gl.v
endif

COCOTB_TOPLEVEL = tb

COCOTB_TEST_MODULES = test

include $(shell cocotb-config --makefiles)/Makefile.sim

.PHONY: clean sim
