meta:
  version: 3
  flow: Classic
  substituting_steps:
    Verilator.Lint: null
    Checker.LintTimingConstructs: null
    Checker.LintErrors: null
    Checker.LintWarnings: null
    +Magic.DRC: KLayout.Antenna
    +Checker.MagicDRC: Checker.KLayoutAntenna


DESIGN_NAME: ntsc
VERILOG_FILES: ["dir::src/ntsc.v", "dir::src/test_pattern.v", "dir::src/expie_i.v", "dir::src/trans.v", "dir::src/pan.v", "dir::src/plural.v", "dir::src/birds.v"]
CLOCK_PERIOD: 40
DIE_AREA: [0, 0, 900, 800]
RUN_MAGIC_DRC: true
GRT_ALLOW_CONGESTION: true
DIODE_ON_PORTS: both
SYNTH_STRATEGY: AREA 1
GRT_ANTENNA_MARGIN: 60
DRT_ANTENNA_MARGIN: 60
DRT_ANTENNA_REPAIR_ITERS: 10
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
RUN_CTS: true
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
IO_PIN_H_LAYER: Metal4
IO_PIN_V_LAYER: Metal3
MAX_TRANSITION_CONSTRAINT: 1.5
MAX_CAPACITANCE_CONSTRAINT: 0.4
RT_MAX_LAYER: Metal4
GRT_OVERFLOW_ITERS: 15

KLAYOUT_DRC_THREADS: 1
KLAYOUT_DRC_OPTIONS:
  workers: max
  decks: "all,-antenna,-density"

KLAYOUT_ANTENNA_OPTIONS:
  workers: max
  decks: "antenna"

STD_CELL_LIBRARY: "gf180mcu_as_sc_mcu7t3v3"

KLAYOUT_RENDER_RESOLUTION: 8192
KLAYOUT_RENDER_OVERSAMPLING: 3
KLAYOUT_PROPERTIES: dir::../../librelane/gf180mcu_render.lyp
