meta:
  version: 3
  flow: Classic
  substituting_steps:
    +Magic.DRC: KLayout.Antenna
    +Checker.MagicDRC: Checker.KLayoutAntenna

DESIGN_NAME: as65rv32
VERILOG_FILES: ["dir::src/cpu.v", "dir::src/wrapped_cpu.v", "dir::src/uart.v"]
CLOCK_PERIOD: 41
DIE_AREA: [0, 0, 900, 900]
DESIGN_REPAIR_TIE_FANOUT: true
DIODE_ON_PORTS: both
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 4
GRT_ALLOW_CONGESTION: true
PL_RESIZER_SETUP_SLACK_MARGIN: 0.15
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.15
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.15
PL_RESIZER_HOLD_SLACK_MARGIN: 0.15
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
GRT_ANTENNA_MARGIN: 30
GRT_ANTENNA_ITERS: 10
DRT_ANTENNA_REPAIR_ITERS: 5
RUN_CTS: true
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::base.sdc
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
IO_PIN_H_LAYER: Metal3
IO_PIN_V_LAYER: Metal4
GRT_OVERFLOW_ITERS: 10
OUTPUT_CAP_LOAD: 180

KLAYOUT_DRC_THREADS: 1
KLAYOUT_DRC_OPTIONS:
  workers: max
  decks: "all,-antenna,-density"

KLAYOUT_ANTENNA_OPTIONS:
  workers: max
  decks: "antenna"

STD_CELL_LIBRARY: "gf180mcu_as_sc_mcu7t3v3"

KLAYOUT_RENDER_RESOLUTION: 8192
KLAYOUT_RENDER_OVERSAMPLING: 3
KLAYOUT_PROPERTIES: dir::../../librelane/gf180mcu_render.lyp
